// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDridxEg3Aq4jE4BEIxKvf8Y97i1SlnmU0',
    appId: '1:912790501929:web:fd68f056418c4e7542ba38',
    messagingSenderId: '912790501929',
    projectId: 'debt-app-36b1f',
    authDomain: 'debt-app-36b1f.firebaseapp.com',
    storageBucket: 'debt-app-36b1f.firebasestorage.app',
    measurementId: 'G-P7431DSVS1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNfwSZ6ukw443JUBn8R0zPmD4BgIlkhsU',
    appId: '1:912790501929:android:483465da2e73e94f42ba38',
    messagingSenderId: '912790501929',
    projectId: 'debt-app-36b1f',
    storageBucket: 'debt-app-36b1f.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALHQgZ3HCKu_4GpbCwFsgqurVyUDZQknU',
    appId: '1:912790501929:ios:4b164a526c9fed9a42ba38',
    messagingSenderId: '912790501929',
    projectId: 'debt-app-36b1f',
    storageBucket: 'debt-app-36b1f.firebasestorage.app',
    iosClientId: '912790501929-7leosh6fbuedq387vrtgnhnbr63g4clb.apps.googleusercontent.com',
    iosBundleId: 'id.gritech.debtTrackerApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALHQgZ3HCKu_4GpbCwFsgqurVyUDZQknU',
    appId: '1:912790501929:ios:4b164a526c9fed9a42ba38',
    messagingSenderId: '912790501929',
    projectId: 'debt-app-36b1f',
    storageBucket: 'debt-app-36b1f.firebasestorage.app',
    iosClientId: '912790501929-7leosh6fbuedq387vrtgnhnbr63g4clb.apps.googleusercontent.com',
    iosBundleId: 'id.gritech.debtTrackerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDridxEg3Aq4jE4BEIxKvf8Y97i1SlnmU0',
    appId: '1:912790501929:web:c7d35f3bee95155242ba38',
    messagingSenderId: '912790501929',
    projectId: 'debt-app-36b1f',
    authDomain: 'debt-app-36b1f.firebaseapp.com',
    storageBucket: 'debt-app-36b1f.firebasestorage.app',
    measurementId: 'G-8TN2R2K7FQ',
  );
}
